### ISSUE TITLE
[BUG] Can’t add modrinth projects

### ISSUE THREAD

**Issue by Z3R0TR0N** [Claptrap-Tracking-Bot/issues#2]
**Describe the bug**
I wanted to add modrinth projects to my new bot, and it won’t add them. Instead, it outputs an error to contact the bot owner. 

**To Reproduce**
1. Go to Dashboard
2. Click on Manage button for server I’ve added the bot to 
3. Scroll down to Modrinth Projects
4. Click ‘+’ 
5. Select relevant channel to send update to
6. Select type: fabric 
7. Enter project ID copied directly from modrinth mod (I used “FiDptjtR“)
8. Optional: select role to ping (leaving blank and selecting a role both didn’t work)
9. Click ‘save’
10. See error: “something went wrong, project may already be followed. Please check if it exists, otherwise please contact bot owner.”

**Expected behavior**
I expected to add the modrinth project to my new list of projects to follow. 

**Screenshots**
![IMG_6024](https://github.com/Claptrap-Tracking-Bot/issues/assets/109635033/4267acf1-20f0-4678-abad-19cc7ff6a8c8)

**Versions (DO NOT USE "LATEST"! I STEAL YOUR KNEE CAPS!):**
- Claptrack Version: Claptrack#9071

**Comment by hypherionmc** [comment]
Issue was resolved. Issue with database
